# Generated by Django 3.1.2 on 2020-12-10 02:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugete',
            fields=[
                ('idJugete', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombreJugete', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('precio', models.TextField(max_length=1000)),
                ('stock', models.URLField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsu', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombreUsu', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('pais', models.TextField(max_length=1000)),
                ('mail', models.URLField(default='', max_length=100)),
            ],
        ),
    ]
